apiVersion: apps/v1
kind: Deployment
metadata:
  name: owletsql
spec:
  selector:
    matchLabels:
      app: owletdb
  replicas: 1
  template:
    metadata:
      labels:
        app: owletdb
  spec:
    terminationGracePeriodSeconds: 10
    containers:
      - name: owletdb
    image: yshchehliuk/owletdb:latest
    ports:
      - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: owletdb-service
spec:
  selector:
    app: owletdb
  ports:
    - protocol: TCP
      port: 1434
      targetPort: 1433
      nodePort: 31433
  typ: NodePort
