version: '3.4' 
 
services: 
    ##nginx proxy
    reverseproxy: 
        build: 
            context: . 
            dockerfile: src/nginx/nginx.Dockerfile 
    ##API
    api.identity: 
        image: ${DOCKER_REGISTRY-}apiidentity 
    api.basket: 
        image: ${DOCKER_REGISTRY-}apibasket 
    api.web: 
        image: ${DOCKER_REGISTRY-}apiweb 
    #api.admin: 
    #    image: ${DOCKER_REGISTRY-}apiadmin

    ##sql database
    owletsql:
        image: mcr.microsoft.com/mssql/server:2019-latest

    #run db by Docker file
    #owletsql:
    #    build:
    #        context: .
    #        dockerfile: sql/sql.Dockerfile

##3rd services
    ##basket's redis
    redis: 
        image: redis:latest 
    redis-commander: 
        image: rediscommander/redis-commander:latest 
    #logging
    owletseq:
        image: datalust/seq
    #email smtp
    owletsmtp:
        image: rnwood/smtp4dev
    #message broker
    rabbitowlet:
        image: rabbitmq:3-management
volumes:
    sqldata:
    redis-data:
networks:
    owletnet: {}